export const insidePhotosNew = [
	{
		src: "/img/gallery-innen-new/I01 balkon-fruehstueck.jpg",
		width: 1.5,
		height: 1,
		key: "I01",
	},
	{
		src: "/img/gallery-innen-new/I02 wohnung-balkon.jpg",
		width: 1.5,
		height: 1,
		key: "I02",
	},
	{
		src: "/img/gallery-innen-new/I03 see-vom-balkon.jpg",
		width: 1.5,
		height: 1,
		key: "I03",
	},
	{
		src: "/img/gallery-innen-new/I04 balkon-abendstimmung.jpg",
		width: 1.5,
		height: 1,
		key: "I04",
	},
	{
		src: "/img/gallery-innen-new/I05 balkon-abendstimmung-2.jpg",
		width: 1.5,
		height: 1,
		key: "I05",
	},
	{
		src: "/img/gallery-innen-new/I06 wohnzimmer-abendstimmung.jpg",
		width: 1.5,
		height: 1,
		key: "I06",
	},
	{
		src: "/img/gallery-innen-new/I07 wohnzimmer-abendstimmung-2.jpg",
		width: 1.5,
		height: 1,
		key: "I07",
	},
	{
		src: "/img/gallery-innen-new/I08 wohnung-wohnzimmer.jpg",
		width: 1.5,
		height: 1,
		key: "I08",
	},
	{
		src: "/img/gallery-innen-new/I09 wohnung-wohnzimmer-2.jpg",
		width: 1.5,
		height: 1,
		key: "I09",
	},
	{
		src: "/img/gallery-innen-new/I10 wohnung-blick-aus-fenster.jpg",
		width: 1.5,
		height: 1,
		key: "I10",
	},
	{
		src: "/img/gallery-innen-new/I11 wohnung-wohnzimmer-3.jpg",
		width: 1.5,
		height: 1,
		key: "I11",
	},
	{
		src: "/img/gallery-innen-new/I12 wohnung-schlafniche.jpg",
		width: 1.5,
		height: 1,
		key: "I12",
	},
	{
		src: "/img/gallery-innen-new/I13 balkon-und-blick.jpg",
		width: 1.5,
		height: 1,
		key: "I13",
	},
	{
		src: "/img/gallery-innen-new/I14 wohnung-kueche.jpg",
		width: 1.5,
		height: 1,
		key: "I14",
	},
	{
		src: "/img/gallery-innen-new/I15 wohnung-kueche-2.jpg",
		width: 1.5,
		height: 1,
		key: "I15",
	},
	{
		src: "/img/gallery-innen-new/I16 kueche-und-kaffee.jpg",
		width: 1.5,
		height: 1,
		key: "I16",
	},
	{
		src: "/img/gallery-innen-new/I17 blick-ins-schlafzimmer.jpg",
		width: 1.5,
		height: 1,
		key: "I17",
	},
	{
		src: "/img/gallery-innen-new/I18 wohnung-schlafzimmer.jpg",
		width: 1.5,
		height: 1,
		key: "I18",
	},
	{
		src: "/img/gallery-innen-new/I19 wohnung-badezimmer.jpg",
		width: 1.5,
		height: 1,
		key: "I19",
	},
	{
		src: "/img/gallery-innen-new/I20 wohnung-badezimmer-2.jpg",
		width: 1.5,
		height: 1,
		key: "I20",
	},
];
