export const recommendations = [
	{
		name: "Gerlitzenbahn",
		type: "other",
		map: "https://goo.gl/maps/Vo3ffgcQawnRdj3T6",
		link: "https://www.gerlitzen.com/",
		image: "/img/gerlitzenbahn.jpeg",
		subtitle: "recBahnS",
		description: "recBahnT",
		favorite: "rec",
	},
	{
		name: "Burg Landskron",
		type: "other",
		map: "https://goo.gl/maps/MVp4n5WKKMUm8X1n6",
		link: "https://www.burg-landskron.at/",
		image: "/img/landskron.jpeg",
		subtitle: "recLandskronS",
		description: "recLandskronT",
		favorite: "rec",
	},
	{
		name: "Burg Hochosterwitz",
		type: "other",
		map: "https://goo.gl/maps/3fUwyivTkGv4DKvs8",
		link: "https://www.burg-hochosterwitz.com/",
		image: "/img/activity.png",
		subtitle: "recOsterwitzS",
		description: "recOsterwitzT",
		favorite: "rec",
	},
	{
		name: "Tenniszentrum Bachmann",
		type: "other",
		map: null,
		link: null,
		image: "/img/tennis.png",
		subtitle: "Tennis spielen, Trainer buchen",
		description:
			"Vom Balkon der Wohnung aus schauen Sie nach links und Sie sehen den Tennisplatz. Buchen Sie im voraus oder gehen Sie einfach vorbei.",
		favorite: "rec",
	},
	{
		name: "Sommerrödelbahn am Ossiacher See",
		type: "other",
		map: "https://goo.gl/maps/HNZz7uwdZVZN8Jtx6",
		link: "https://www.sommerrodelbahn-ossiach.at/",
		image: "/img/activity.png",
		subtitle: "recRoedelS",
		description: "recRoedelT",
		favorite: "rec",
	},
	{
		name: "Ossiacher See Schifffahrt",
		type: "other",
		map: "https://goo.gl/maps/1p3iu1NcdRAvihiP9",
		link: "https://ossiachersee-schifffahrt.at/",
		image: "/img/activity.png",
		subtitle: "recSchiffS",
		description: "recSchiffT",
		favorite: "rec",
	},
	{
		name: "Altstadt Villach",
		type: "other",
		map: "https://goo.gl/maps/x5cqmaYexukgVc498",
		link: "https://www.visitvillach.at/de/tours/villacher-altstadtspaziergang.html",
		image: "/img/activity.png",
		subtitle: "recVillachS",
		description: "recVillachT",
		favorite: "rec",
	},
	{
		name: "Urbani Wirt",
		type: "restaurant",
		map: "https://goo.gl/maps/v7qw19GVjdNgmXYK7",
		link: "https://urbaniwirt.com/",
		image: "/img/cutlery.png",
		subtitle: "recUrbaniS",
		description: "recUrbaniT",
		favorite: "rec",
	},
	{
		name: "Naturgasthof Schlosswirt Ossiach",
		type: "restaurant",
		map: "https://goo.gl/maps/nYAfLfhVCGSAw4Sc6",
		link: "https://www.schlosswirt-ossiach.at/",
		image: "/img/cutlery.png",
		subtitle: "recSchlosswirtS",
		description: "recSchlosswirtT",
		favorite: "rec",
	},
	{
		name: "zum Hexenpfandl",
		type: "restaurant",
		map: "https://goo.gl/maps/TkZWqFL2ueBqQpCs7",
		link: "https://www.hexenpfandl.at/",
		image: "/img/cutlery.png",
		subtitle: "recHexenpfandlS",
		description: "recHexenpfandlT",
		favorite: "rec",
	},
	{
		name: "Seerestaurant Steindorf",
		type: "restaurant",
		map: "https://goo.gl/maps/eGxVWwFdEsLSe2F99",
		link: null,
		image: "/img/cutlery.png",
		subtitle: "recSeerestaurantS",
		description: "recSeerestaurantT",
		favorite: "rec",
	},
	{
		name: "Café Pavillion am See",
		type: "restaurant",
		map: "https://goo.gl/maps/vndWTYF2QvbGviENA",
		link: null,
		image: "/img/cutlery.png",
		subtitle: "recPavillionS",
		description: "recPavillionT",
		favorite: "rec",
	},
	{
		name: "Gasthof Seitner",
		type: "restaurant",
		map: "https://goo.gl/maps/WNcaWVYdpawPqbe86",
		link: "https://www.gasthof-seitner.at/",
		image: "/img/cutlery.png",
		subtitle: "recSeitnerS",
		description: "recSeitnerT",
		favorite: "rec",
	},
	{
		name: "Seemandl am Flatschacher See",
		type: "restaurant",
		map: "https://goo.gl/maps/U3mbka65JBMHuizL7",
		link: "http://www.seemandl.at/",
		image: "/img/cutlery.png",
		subtitle: "recSeemandlS",
		description: "recSeemandlT",
		favorite: "rec",
	},
	{
		name: "Stofflwirt",
		type: "restaurant",
		map: "https://goo.gl/maps/8uxeaHU9rQqKJyse7",
		link: "http://www.stofflwirt.at/",
		image: "/img/cutlery.png",
		subtitle: "recStofflwirtS",
		description: "recStofflwirtT",
		favorite: "rec",
	},
	{
		name: "Billa",
		type: "shopping",
		map: "https://goo.gl/maps/pGZcGMxsH4u8ZWcD9",
		link: "https://billa.at",
		image: "/img/shopping.jpeg",
		subtitle: "recBillaS",
		description: "recBillaT",
		favorite: "rec",
	},
	{
		name: "Spar",
		type: "shopping",
		map: "https://goo.gl/maps/fNSjSp9HJ7zS5fCo9",
		link: "https://www.spar.at/",
		image: "/img/shopping.jpeg",
		subtitle: "recSparS",
		description: "recSparT",
		favorite: "rec",
	},
	{
		name: "Schieder Bäckerei",
		type: "shopping",
		map: "https://goo.gl/maps/y2npaSfsKQJ1MYzJA",
		link: "https://www.schieder.at/",
		image: "/img/shopping.jpeg",
		subtitle: "recSchiederS",
		description: "recSchiederT",
		favorite: "rec",
	},
	{
		name: "Nockfleisch",
		type: "shopping",
		map: "https://goo.gl/maps/ezPfb89KaF1rYAa58",
		link: "https://nockbauern.at/",
		image: "/img/shopping.jpeg",
		subtitle: "recNockfleischS",
		description: "recNockfleischT",
		favorite: "rec",
	},
	{
		name: "Café Konditorei Saliterer",
		type: "shopping",
		map: "https://goo.gl/maps/wSJpL37fRWFXGnvq5",
		link: null,
		image: "/img/shopping.jpeg",
		subtitle: "recSalitererS",
		description: "recSalitererT",
		favorite: "rec",
	},
];
